---
version: "2.1"
services:
  app:
    image: lscr.io/linuxserver/libreoffice:latest
    container_name: application-server
    security_opt:
      - seccomp:unconfined #optional
      - apparmor:unconfined
    devices:
      - /dev/fuse
    cap_add:
      - SYS_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    ports:
      - 3000:3000
      - 3001:3001
    restart: unless-stopped
    networks:
      - app-network
networks:
  app-network:
    external: true
