version: '2.4'
services:
  app:
    container_name: "application-server"
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ..:/workspace:cached
      - ./cirro_data:/cirro_data
    command: cirro serve -b application-server:5000
    ports:
      - '5000:5000'
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    security_opt:
      - apparmor:unconfined
    depends_on:
      - mongodb
  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    volumes:
      - mongodata:/data/db
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=cirrocumulus
volumes:
  work:
  mongodata:
