version: '2.4'
services:
  app:
    container_name: "application-server"
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ..:/workspace:cached
      - ./cirro_data:/cirro_data
    command: cirro serve -b application-server:5000 --db_uri mongodb://user:pass@mongodb/cirro
    ports:
      - '5000:5000'
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    security_opt:
      - apparmor:unconfined
    depends_on:
      - mongodb
  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
      - MONGO_INITDB_DATABASE=cirro
volumes:
  work:
