version: '2.4'
services:
  app:
    container_name: "application-server"
    image: "ghcr.io/rocker-org/devcontainer/tidyverse:4.2"
    restart: always
    volumes:
      - ..:/workspace:cached
      - work:/home/rstudio
    ports:
      - '8787:8787'
    env_file: devcontainer.env
    environment:
      "DISABLE_AUTH": "true"
    networks:
      - app-network
    devices:
      - /dev/fuse
networks:
  app-network:
    external: true
volumes:
  work:
