version: '2.4'
services:
  app:
    container_name: "r-server"
    image: "rocker/rstudio"
    environment:
      USER: "rstudio"
      PASSWORD: "password"
      DISABLE_AUTH: "true"
    ports:
    - '8081:${PORT}'
    restart: always
    network_mode: bridge
    volumes:
      - work:/workspaces:cached
  agent:
    image: gcr.io/inverting-proxy/agent
    restart: always
    platform: linux/amd64
    environment:
      PROXY: 'https://app-proxy-devel.workbench.health/'
      HOSTNAME: 'r-server'
      PORT: '${PORT}'
      BACKEND: "${BACKEND_ID}"
      SHIM_PATH: 'websocket-shim'
      REWRITE_WEBSOCKET_HOST: 'true'     
volumes:
  work:
