# Use an official Python runtime as a parent image
FROM python:3.9


# Install any needed packages specified in requirements.txt
RUN python -m pip install --upgrade pip && python -m pip install cirrocumulus

